#!/bin/bash

sd=~
dsrv=$sd/www/scarica
apphome=$sd/pys

while
  clear
  cat $apphome/title-pys | lolcat
  echo python web server
  echo ...
do
  echo all il...
  ifconfig | grep "inet'
  echo wlan:
  ifconfig | grep "broadcast"
  cd $dsrv
  python3 -m http.server 1212 | echo server_online http://0.0.0.0:1212' ->'sd/www/scarica | lolcat
done
